# Generated by Django 5.1.4 on 2025-01-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_access_customer', 'Can access customer')]},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_access_departament', 'Can access departament hierarchy')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_access_organization', 'Can access organization hierarchy')]},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'permissions': [('can_access_tenant', 'Can access tenant hierarchy')]},
        ),
    ]
