# Generated by Django 5.1.4 on 2025-01-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_customer_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_access_departament', 'Can access departament')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': [('can_access_organization', 'Can access organization')]},
        ),
    ]
