# Generated by Django 5.1.4 on 2025-01-12 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_access_departament', 'Can access department')]},
        ),
    ]
