# Generated by Django 5.1.4 on 2025-01-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_access_department', 'Can access department')]},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'permissions': [('can_access_tenant', 'Can access tenant')]},
        ),
    ]
